
import javax.swing.DefaultListModel;


public class SocialNetworkUI extends javax.swing.JFrame {

    private String currentUserName = null;
    private int currentID = -1;
    private SocialNetwork friendsNetwork = new SocialNetwork();
    private DefaultListModel UIFriendsModel = new DefaultListModel(); 
    private DefaultListModel UIRecommendationsModel = new DefaultListModel(); 
    
    /**
     * Creates new form SocialMediaUI
     */
    public SocialNetworkUI() {
        initComponents();
        System.out.println("Load the Social Network Database");
        friendsNetwork.Load();
        
        clearLists();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginNameField = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        userInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UIFriendsList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        UIRecommendedList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Social Network (CS_ADS2_Task 2)");

        loginNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginNameField.setText("User Full Name");
        loginNameField.setToolTipText("Input user's full name and click \"login\"");
        loginNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNameFieldMouseClicked(evt);
            }
        });
        loginNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNameFieldActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        UIFriendsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        UIFriendsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UIFriendsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UIFriendsList);

        UIRecommendedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        UIRecommendedList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UIRecommendedListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(UIRecommendedList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText(" My Friends");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText(" People you may know");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNameFieldMouseClicked
        loginNameField.setText("");//Clear the previous input
    }//GEN-LAST:event_loginNameFieldMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        clearLists();
        
        currentUserName = loginNameField.getText();
        currentID = friendsNetwork.FindUserID(currentUserName);
        if (currentID==-1){
            userInfo.setText(" User Information: Unknown");
            UIFriendsModel.clear();
            
        }            
        else {
            userInfo.setText(" User Name: "+currentUserName+" | User ID: #"+currentID);
            
            String[] friends = friendsNetwork.GetMyFriends(currentUserName);
            for (int i=0, n=friends.length; i<n; i++)
                UIFriendsModel.addElement(friends[i]);
            
            String[] recommendations = friendsNetwork.GetRecommended(currentUserName);
            for (int i=0, n=recommendations.length; i<n; i++)
                UIRecommendationsModel.addElement(recommendations[i]);
        }
        UIFriendsList.setModel(UIFriendsModel);
    }//GEN-LAST:event_loginActionPerformed

    private void loginNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNameFieldActionPerformed
        
    }//GEN-LAST:event_loginNameFieldActionPerformed

    private void UIFriendsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UIFriendsListMouseClicked
        int selected = UIFriendsList.getSelectedIndex();
        System.out.println("The item_"+selected+" from the friend list is selected");
        
    }//GEN-LAST:event_UIFriendsListMouseClicked

    private void UIRecommendedListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UIRecommendedListMouseClicked
        int selected = UIRecommendedList.getSelectedIndex();
        System.out.println("The item_"+selected+" from the recommendation list is selected");
    }//GEN-LAST:event_UIRecommendedListMouseClicked

    private void clearLists(){
        UIFriendsModel.clear();
        UIFriendsList.setModel(UIFriendsModel);
        UIRecommendationsModel.clear();
        UIRecommendedList.setModel(UIRecommendationsModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SocialNetworkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SocialNetworkUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> UIFriendsList;
    private javax.swing.JList<String> UIRecommendedList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login;
    private javax.swing.JTextField loginNameField;
    private javax.swing.JLabel userInfo;
    // End of variables declaration//GEN-END:variables
}
